# Generated by Django 4.2.6 on 2023-10-14 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 8, 5, 42, 839005)),
        ),
    ]
