# Generated by Django 4.2.6 on 2023-10-14 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2023, 10, 14, 11, 15, 8, 552089, tzinfo=datetime.timezone.utc)),
        ),
    ]
