# Generated by Django 4.2.6 on 2023-10-19 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_alter_link_date_posted_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='date_posted',
            field=models.DateField(default=datetime.datetime(2023, 10, 19, 16, 8, 18, 855672, tzinfo=datetime.timezone.utc)),
        ),
    ]
